pdp/member/urls.py
# coding: utf-8

from django.conf.urls import patterns, url

import views

urlpatterns = patterns('',
    url(r'^voir/(?P<user_name>.+)$', views.details),
    url(r'^profil/editer$', views.edit_profile),
    url(r'^parametres/profil$', views.settings_profile),
    url(r'^parametres/compte$', views.settings_account),
    url(r'^connexion$', views.login_view),
    url(r'^inscription$', views.register_view),
    url(r'^deconnexion/$', views.logout_view),
    url(r'^$', views.index),
)

pdp/urls.py
# coding: utf-8

from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

import pages.views
import settings

urlpatterns = patterns('',
    url(r'^articles/', include('pdp.article.urls')),
    url(r'^tutoriels/', include('pdp.tutorial.urls')),
    url(r'^forums/', include('pdp.forum.urls')),
    url(r'^membres/', include('pdp.member.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^pages/', include('pdp.pages.urls')),

    url(r'^captcha/', include('captcha.urls')),

    url(r'^$', pages.views.home),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    )

pdp/member/models.py
# coding: utf-8

from hashlib import md5

from django.db import models
from django.contrib.auth.models import User

from pdp.forum.models import Post, Topic
from pdp.tutorial.models import Tutorial
from pdp.article.models import Article


class Profile(models.Model):
    '''Represents an user profile'''
    class Meta:
        verbose_name = 'Profil'
        verbose_name_plural = 'Profils'

    user = models.ForeignKey(User, unique=True, verbose_name='Utilisateur')

    site = models.CharField('Site internet', max_length=128, blank=True)
    show_email = models.BooleanField('Afficher adresse mail publiquement',
                                     default=True)

    avatar_url = models.CharField('URL de l\'avatar', max_length=128, null=True, blank=True)

    biography = models.TextField('Biographie', blank=True)

    def __unicode__(self):
        '''Textual forum of a profile'''
        return self.user.username

    def get_absolute_url(self):
        '''Absolute URL to the profile page'''
        return '/membres/voir/{0}'.format(self.user.username)

    def get_avatar_url(self):
        '''Avatar URL (using custom URL or Gravatar)'''
        if self.avatar_url:
            return self.avatar_url
        else:
            return 'http://gravatar.com/avatar/{0}?d=identicon'.format(md5(self.user.email).hexdigest())

    def get_post_count(self):
        '''Number of messages posted'''
        return Post.objects.all().filter(author__pk=self.user.pk).count()

    def get_topic_count(self):
        '''Number of threads created'''
        return Topic.objects.all().filter(author=self.user).count()

    # Tutorial

    def get_tutorials(self):
        return Tutorial.objects.filter(authors=self.user.pk)

    def get_visible_tutorials(self):
        return self.get_tutorials().filter(is_visible=True)

    def get_hidden_tutorials(self):
        return self.get_tutorials().filter(is_visible=False)

    # Article

    def get_articles(self):
        return Article.objects.all().filter(author=self.user)

    def get_visible_articles(self):
        return self.get_articles().filter(is_visible=True)

    def get_hidden_articles(self):
        return self.get_articles().filter(is_visible=False)

pdp/member/forms.py
# coding: utf-8

from django import forms

from django.contrib.auth.models import User
from django.contrib.auth import authenticate

from crispy_forms.helper import FormHelper
from crispy_forms_foundation.layout import Layout, Div, Fieldset, Submit, Field, HTML

from captcha.fields import CaptchaField

from pdp.member.models import Profile

class LoginForm(forms.Form):
    username = forms.CharField(max_length=30)
    password = forms.CharField(max_length=76, widget=forms.PasswordInput)

class RegisterForm(forms.Form):
    email = forms.EmailField(label='Adresse email')
    username = forms.CharField(label='Nom d\'utilisateur', max_length=30)
    password = forms.CharField(label='Mot de passe', max_length=76, widget=forms.PasswordInput)
    password_confirm = forms.CharField(label='Confirmation', max_length=76, widget=forms.PasswordInput)
    captcha = CaptchaField()

    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_class = 'form-horizontal'
        self.helper.form_method = 'post'


        self.helper.layout = Layout(
            Fieldset(
                u'Identifiants',
                Field('username'),
                Field('password'),
                Field('password_confirm'),
                Field('email'),
            ),
            Fieldset(
                u'Captcha',
                Field('captcha'),
            ),
            Div(
                Submit('submit', 'Valider mon inscription'),
                HTML('<a href="/" class="button secondary">Annuler</a>'),
                css_class='button-group'
            )
        )
        super(RegisterForm, self).__init__(*args, **kwargs)


    def clean(self):
        cleaned_data = super(RegisterForm, self).clean()

        # Check that the password and it's confirmation match
        password = cleaned_data.get('password')
        password_confirm = cleaned_data.get('password_confirm')

        if not password_confirm == password:
            msg = u'Les mots de passe sont différents'
            self._errors['password'] = self.error_class([''])
            self._errors['password_confirm'] = self.error_class([msg])

            if 'password' in cleaned_data:
                del cleaned_data['password']

            if 'password_confirm' in cleaned_data:
                del cleaned_data['password_confirm']

        # Check that the user doesn't exist yet
        username = cleaned_data.get('username')
        if User.objects.filter(username=username).count() > 0:
            msg = u'Ce nom d\'utilisateur est déjà utilisé'
            self._errors['username'] = self.error_class([msg])

        return cleaned_data

# update extra information about user
class ProfileForm(forms.Form):
    biography = forms.CharField(
        label='Biographie',
        required=False,
        widget=forms.Textarea(
            attrs={'placeholder':'Votre biographie au format Markdown.'}))
    site = forms.CharField(
        label='Site internet',
        required=False,
        max_length=128,
        widget=forms.TextInput(
            attrs={'placeholder':'Lien vers votre site internet personnel '
                   '(ne pas oublier le http:// ou https:// devant).'}))
    show_email = forms.BooleanField(
        label='Afficher mon adresse mail publiquement',
        required=False)
    avatar_url = forms.CharField(
        label='Avatar',
        required=False,
        widget=forms.TextInput(
            attrs={'placeholder': 'Lien vers un avatar externe '
                   '(laisser vide pour utiliser Gravatar).'}))

    def __init__(self, user, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_method = 'post'

        self.user = user
        profile = Profile.objects.get(user=self.user)

        #to get initial value form checkbox show email
        initial = kwargs.get('initial', {})
        value_checked = ''
        if 'show_email' in initial and initial['show_email']:
            value_checked = 'checked'

        self.helper.layout = Layout(
            Fieldset(
                u'Public',
                Field('biography'),
                Field('site'),
                Field('avatar_url'),
                #inline checkbox is not supported by crispy form
                HTML('<div id="div_id_show_email" class="ctrlHolder checkbox" style="padding-top:10px">\
                <label for="id_show_email" > <input id="id_show_email" type="checkbox" class="checkboxinput" name="show_email" '+ value_checked +'/>\
                Afficher mon adresse mail publiquement</label></div>'),
            ),
            Div(
                Submit('submit', 'Editer mon profil'),
                css_class='button-group'
            )
        )
        super(ProfileForm, self).__init__(*args, **kwargs)

# to update a password
class ChangePasswordForm(forms.Form):
    password_new = forms.CharField(label='Nouveau mot de passe ', max_length=76, widget=forms.PasswordInput)
    password_old = forms.CharField(label='Mot de passe actuel ', max_length=76, widget=forms.PasswordInput)
    password_confirm = forms.CharField(label='Confirmer le nouveau mot de passe ', max_length=76, widget=forms.PasswordInput)

    def __init__(self, user, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_class = 'form-horizontal'
        self.helper.form_method = 'post'

        self.user = user

        self.helper.layout = Layout(
            Fieldset(
                u'Mot de passe',
                Field('password_old'),
                Field('password_new'),
                Field('password_confirm'),
            ),
            Div(
                Submit('submit', 'Changer mon mot de passe'),
                css_class='button-group'
            )
        )
        super(ChangePasswordForm, self).__init__(*args, **kwargs)


    def clean(self):
        cleaned_data = super(ChangePasswordForm, self).clean()

        password_old = cleaned_data.get('password_old')
        password_new = cleaned_data.get('password_new')
        password_confirm = cleaned_data.get('password_confirm')


        # Check if the actual password is not empty
        if password_old:
            user_exist = authenticate(username=self.user.username, password=password_old)
            if not user_exist and password_old != "":
                self._errors['password_old'] = self.error_class([u'Mot de passe incorrect.'])
                if 'password_old' in cleaned_data:
                    del cleaned_data['password_old']

        # Check that the password and it's confirmation match
        if not password_confirm == password_new:
            msg = u'Les mots de passe sont différents.'
            self._errors['password_new'] = self.error_class([msg])
            self._errors['password_confirm'] = self.error_class([msg])

            if 'password_new' in cleaned_data:
                del cleaned_data['password_new']

            if 'password_confirm' in cleaned_data:
                del cleaned_data['password_confirm']

        return cleaned_data

pdp/member/views.py
# coding: utf-8

from django.shortcuts import redirect, get_object_or_404, render_to_response
from django.http import Http404

from django.contrib.auth.models import User, SiteProfileNotAvailable
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages

from django.core.context_processors import csrf
from django.template import RequestContext

from pdp.utils.tokens import generate_token
from pdp.utils import render_template

from models import Profile
from forms import LoginForm, ProfileForm, RegisterForm, ChangePasswordForm

from pdp.forum.models import Forum

def index(request):
    '''Displays the list of registered users'''
    members = User.objects.order_by('date_joined')
    return render_template('member/index.html', {
        'members': members
    })


def details(request, user_name):
    '''Displays details about a profile'''
    usr = get_object_or_404(User, username=user_name)

    try:
        profile = usr.get_profile()
    except SiteProfileNotAvailable:
        raise Http404

    forums = Forum.objects.all()

    return render_template('member/profile.html', {
        'usr': usr, 'profile': profile
    })


@login_required
def edit_profile(request):
    try:
        profile_pk = int(request.GET['profil'])
        profile = get_object_or_404(Profile, pk=profile_pk)
    except KeyError:
        profile = get_object_or_404(Profile, user=request.user)

    # Making sure the user is allowed to do that
    if not request.user == profile.user:
        raise Http404
    if request.method == 'POST':
        form = ProfileForm(request.POST)
        if form.is_valid():
            data = form.data
            profile.biography = data['biography']
            profile.site = data['site']
            profile.user.email = data['email']
            profile.show_email = 'show_email' in data

            # Save the user and it's associated profile
            profile.user.save()
            profile.save()
            return redirect(profile.get_absolute_url())
        else:
            raise Http404
    else:
        return render_template('member/edit_profile.html', {
            'profile': profile
        })


def login_view(request):
    csrf_tk = {}
    csrf_tk.update(csrf(request))

    error = False
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                request.session['get_token'] = generate_token()
                return redirect('/')
            else:
                error = 'Les identifiants fournis ne sont pas valides'
        else:
            error = 'Veuillez spécifier votre identifiant et votre mot de passe'
    else:
        form = LoginForm()
    csrf_tk['error'] = error
    csrf_tk['form'] = form
    return render_template('member/login.html', csrf_tk)


@login_required
def logout_view(request):
    logout(request)
    request.session.clear()
    return redirect('/')


def register_view(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            data = form.data
            user = User.objects.create_user(
                data['username'],
                data['email'],
                data['password'])
            profile = Profile(user=user, show_email=False)
            profile.save()
            user.backend = 'django.contrib.auth.backends.ModelBackend'
            login(request, user)
            return render_template('member/register_success.html')
        else:
            return render_template('member/register.html', {'form': form})

    form = RegisterForm()
    return render_template('member/register.html', {
        'form': form
    })

#settings for public profile
@login_required
def settings_profile(request):
    #extra information about the current user
    profile = Profile.objects.get(user=request.user)

    if request.method == 'POST':
        form = ProfileForm(request.user, request.POST)
        c = {
            'form' : form,
        }
        if form.is_valid():
            profile.biography = form.data['biography']
            profile.site = form.data['site']
            profile.show_email = 'show_email' in form.data
            profile.avatar_url = form.data['avatar_url']

            # Save the profile
            # and redirect the user to the configuration space
            # with message indicate the state of the operation
            try:
                profile.save()
            except:
                messages.error(request,'Une erreur est survenue.')
                return redirect('/membres/parametres/profil')

            messages.success(request,'Le profil a correctement été mis à jour.')
            return redirect('/membres/parametres/profil')
        else:
            return render_to_response('member/settings_profile.html',c,RequestContext(request))
    else:
        form = ProfileForm(request.user,initial={
            'biography': profile.biography,
            'site': profile.site,
            'avatar_url': profile.avatar_url,
            'show_email': profile.show_email}
        )
        c = {
            'form' : form
        }
        return render_to_response('member/settings_profile.html',c,RequestContext(request))

@login_required
def settings_account(request):
    if request.method == 'POST':
        form = ChangePasswordForm(request.user,request.POST)
        c = {
            'form' : form,
        }
        if form.is_valid():
            try:
                request.user.set_password(form.data['password_new'])
                request.user.save()
                messages.success(request,'Le mot de passe a bien été modifié.')
                return redirect('/membres/parametres/profil')
            except:
                messages.error(request,'Une erreur est survenue.')
                return redirect('/membres/parametres/profil')
        else:
            return render_to_response('member/settings_account.html',c,RequestContext(request))
    else:
        form = ChangePasswordForm(request.user)
        c = {
            'form' : form,
        }
        return render_to_response('member/settings_account.html',c,RequestContext(request))

templates/member/base.html
{% extends "base.html" %}

{% block title_base %}
    &#183; Membres
{% endblock %}

{% block breadcrumb_base %}
    <li><a href="{% url pdp.member.views.index %}">Membres</a></li>
{% endblock %}

templates/member/edit_profile.html
{% extends "member/base.html" %}
{% load markup %}

{% block title %}
    Éditer mon profil
{% endblock %}

{% block headline %}
    Éditer mon profil
{% endblock %}

{% block breadcrumb %}
    <li><a href="{{ profile.user.get_absolute_url }}">{{ profile.user.username }}</a></li>
    <li class="current"><a href="#">Éditer mon profil</a></li>
{% endblock %}

{% block content %}

<div class="row">
    <div class="large-12 columns">
        <form action="" method="POST" class="form-horizontal">
            <fieldset>
                <legend>Public</legend>
        
                <div class="control-group">
                    <label for="id_biography" class="control-label">Biographie</label>
                    <div class="controls">
                        <textarea name="biography" class="input-block-level" rows="10" id="id_biography"
                            placeholder="Votre biographie au format Markdown.">{{ profile.biography }}</textarea>
                    </div>
                </div>
        
                <div class="control-group">
                    <label for="id_site" class="control-label">Site internet</label>
                    <div class="controls">
                        <input type="text" name="site" id="id_site" class="input-block-level"
                        placeholder="Lien vers votre site internet personnel." value="{{ profile.site }}"/>
                    </div>
                </div>
        
                <div class="control-group">
                    <label for="id_email" class="control-label">Adresse mail</label>
                    <div class="controls">
                        <input type="text" name="email" id="id_email" class="input-block-level"
                        placeholder="Veuillez entrer une adresse email valide" value="{{ profile.user.email }}"/>
                    </div>
                </div>
        
                <div class="control-group">
                    <div class="controls">
                        <label class="checkbox">
                            <input type="checkbox" name="show_email"
                            {% if profile.show_email %}checked{% endif %}>
                            Afficher mon adresse mail publiquement
                        </label>
                    </div>
                </div>
        
            </fieldset>
            <div style="text-align: center;">
                <button type="submit" class="button">
                    <i class="icon-pencil icon-white"></i>
                    Éditer
                </button>
        
                <a href="{{ profile.user.get_absolute_url }}" class="button secondary">
                    Annuler
                </a>
            </div>
        
            {% csrf_token %}
        
        </form>
    </div>
</div>



{% endblock %}

templates/member/index.html
{% extends "member/base.html" %}

{% block title %}
    Membres
{% endblock %}

{% block headline %}
    Membres
{% endblock %}

{% block breadcrumb %}
    <li class="current"><a href="#">Index</a></li>
{% endblock %}

{% block content %}

<div class="row">
    <div class="large-12 columns">
        <p>
            Sur cette page vous pourrez trouver la liste des membres inscrits au site (actuellement {{ members.count }} membres).
        </p>
    </div>
</div>

<div class="row">
    <div class="large-12 columns">
        <p>
            {% for member in members %}
                {% include "member/member_item_common.part.html" %}
            {% endfor %}
        </p>
    </div>
</div>

{% endblock %}

templates/member/login.html
{% extends "member/base.html" %}

{% block title %}
    Connexion
{% endblock %}

{% block headline %}
    Se connecter
{% endblock %}

{% block breadcrumb %}
    <li class="current"><a href="#">Connexion</a></li>
{% endblock %}

{% block content %}
    
<div class="row">
    <div class="large-12 columns">
        {% if not user.is_authenticated %}
            {% if error %}
            <div class="alert-box alert">
                {{ error }}.
            </div>
            {% endif %}
        
            <p>
                Si vous n'avez pas de compte, vous pouvez <a href="{% url pdp.member.views.register_view %}" >vous inscrire</a>.
            </p>
        {% else %}
            <p>
                Vous êtes déjà connecté.
            </p>
        {% endif %}
    </div>
</div>

{% if not user.is_authenticated %}
<div class="row">
    <div class="large-7 large-offset-1 columns">
        <form method="post" action="{% url pdp.member.views.login_view %}" class="form-horizontal">
            <div class="row">
                <div class="small-4 columns">
                    <label class="right inline" for="id_username">Identifiant</label>
                </div>
                <div class="small-8 columns">
                    <input type="text" name="username" id="id_username" maxlength="30" />
                </div>
            </div>
            <div class="row">
                <div class="small-4 columns">
                    <label class="right inline" for="id_password">Mot magique</label>
                </div>
                <div class="small-8 columns">
                    <input type="password" name="password" id="id_password" maxlength="76" />
                </div>
            </div>

            <div class="row">
                <div class="small-8 small-offset-4 columns">
                    <button type="submit" class="button">
                        Se connecter
                    </button>
                    <a href="/" class="button secondary">
                        Annuler
                    </a>
                </div>
            </div>
    
            {% csrf_token %}
        </form>
    </div>
</div>
{% endif %}

{% endblock %}

templates/member/member_item_common.part.html
{% load profile %}

{% with profile=member|profile %}
<a href="{{ member.get_absolute_url }}" class="member-item">
    <img src="{{ profile.get_avatar_url }}" width="16" height="16" alt="Avatar" />
    {{ member.username }}
</a>
{% endwith %}

templates/member/profile.html
{% extends "member/base.html" %}
{% load emarkdown %}
{% load markup %}
{% load humane_date %}
{% load email_obfuscator %}

{% block title %}
    {{ usr.username }}
{% endblock %}

{% block headline %}
    {{ usr.username }}
{% endblock %}

{% block breadcrumb %}
    <li class="current"><a href="#">{{ usr.username }}</a></li>
{% endblock %}

{% block headline-actions %}
    {% ifequal profile.user user %}
        <a href="{% url pdp.member.views.settings_profile %}" class="button">
            Paramètres
        </a>
    {% endifequal %}
{% endblock %}

{% block content %}

<div class="row">
    <div class="large-2 columns">
        <img src="{{ profile.get_avatar_url }}" alt="Avatar" width="80" height="80" class="th"/>
    </div>
    <div class="large-10 columns">
        <p>
            {% if profile.show_email and user.is_authenticated %}
                Adresse mail : {{ usr.email|obfuscate_mailto }}<br />
            {% endif %}

            {% if profile.site %}
                Site internet : <a href="{{ profile.site }}">{{ profile.site }}</a><br />
            {% endif %}

            Inscrit {{ usr.date_joined|humane_date }},
            dernière connexion {{ usr.last_login|humane_date }}.
        </p>
    </div>
</div>

<div class="row">
    <div class="large-4 columns">
        <h3>Articles</h3>
        <table>
            <tbody>
                <tr>
                    <td>En cours de rédaction</td>
                    <td>{{ profile.get_hidden_articles.count }}</td>
                </tr>
                <tr>
                    <td>En ligne</td>
                    <td>{{ profile.get_visible_articles.count }}</td>
                </tr>
            </tbody>
            <tfoot>
                <tr>
                    <td>Total</td>
                    <td>{{ profile.get_articles.count }}</td>
                </tr>
            </tfoot>
        </table>
    </div>
    <div class="large-4 columns">
        <h3>Tutoriels</h3>
        <table>
            <tbody>
                <tr>
                    <td>En cours de rédaction</td>
                    <td>{{ profile.get_hidden_tutorials.count }}</td>
                </tr>
                <tr>
                    <td>En ligne</td>
                    <td>{{ profile.get_visible_tutorials.count }}</td>
                </tr>
            </tbody>
            <tfoot>
                <tr>
                    <td>Total</td>
                    <td>{{ profile.get_tutorials.count }}</td>
                </tr>
            </tfoot>
        </table>
    </div>
    <div class="large-4 columns">
        <h3>Forums</h3>
        <table>
            <tbody>
                <tr>
                    <td>Sujets créés</td>
                    <td>{{ profile.get_topic_count }}</td>
                </tr>
                <tr>
                    <td>Messages postés</td>
                    <td>{{ profile.get_post_count }}</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

{# Biography #}

{% if profile.biography %}

<div class="row">
    <div class="large-12 columns">
        <h2>Biographie</h2>
        {{ profile.biography|emarkdown }}
    </div>
</div>

{% endif %}

{% endblock %}

templates/member/register.html
{% extends "member/base.html" %}
{% load crispy_forms_tags %}

{% block title %}
    S'incrire
{% endblock %}

{% block headline %}
    S'inscrire
{% endblock %}

{% block breadcrumb %}
    <li class="current"><a href="#">S'inscrire</a></li>
{% endblock %}

{% block content %}
    
<div class="row">
    <div class="large-12">
        {% if not user.is_authenticated %}
            {% if error %}
                {{ error }}
            {% endif %}
            <p>
                <strong>Vous êtes sur le point de vous inscrire sur Progdupeupl</strong> ; si vous
                possédez déjà un compte, merci de <a href="{% url pdp.member.views.login_view %}">vous connecter</a>
                à la place.
            </p>
            <p>
                Veuillez fournir les informations nécessaires dans le
                formulaire suivant afin de poursuivre votre inscription.
            </p>
            {% crispy form %}
        {% else %}
            <p>Vous êtes déjà connecté.</p>
        {% endif %}
    </div>
</div>

{% endblock %}

templates/member/register_success.html
{% extends "member/base.html" %}

{% block title %}
Inscription réussie
{% endblock %}

{% block headline %}
Inscription réussie
{% endblock %}

{% block breadcrumb %}
Inscription
{% endblock %}

{% block content %}

<p>
Vous avez bien été inscrit au site. <a href="{% url pdp.member.views.details user.username %}">Voir votre profil</a>.
</p>

{% endblock %}

templates/member/settings_account.html
{% extends "member/settings_base.html" %}
{% load crispy_forms_tags %}

{% block breadcrumb %}
    <li><a href="{% url pdp.member.views.settings_profile %}">Paramètres</a></li>
    <li class="current"><a href="#">Compte</a></li>
{% endblock %}

{% block subnav %}
    <dd><a href="{% url pdp.member.views.settings_profile %}">Profil</a></dd>
    <dd class="active"><a href="{% url pdp.member.views.settings_account %}">Compte</a></dd>
{% endblock %}

{% block settings_form %}
<div class="row">
    <div class="large-12 columns">
        {% crispy form %}
    </div>
</div>
{% endblock %}

templates/member/settings_base.html
{% extends "member/base.html" %}
{% load markup %}

{% block title %}
   Paramètres
{% endblock %}

{% block headline %}
   Paramètres
{% endblock %}

{% block content %}
    <div class="row">
        <div class="large-12 columns">
            <dl class="sub-nav">
                {% block subnav %}{% endblock %}
            </dl>
        </div>
    </div>
    {% block settings_form %}{% endblock %}
{% endblock %}

templates/member/settings_profile.html
{% extends "member/settings_base.html" %}
{% load crispy_forms_tags %}

{% block breadcrumb %}
    <li><a href="{% url pdp.member.views.settings_profile %}">Paramètres</a></li>
    <li class="current"><a href="#">Profil</a></li>
{% endblock %}

{% block subnav %}
    <dd class="active"><a href="{% url pdp.member.views.settings_profile %}">Profil</a></dd>
    <dd><a href="{% url pdp.member.views.settings_account %}">Compte</a></dd>
{% endblock %}

{% block settings_form %}
    <div class="row">
        <div class="large-12 columns">
            {% crispy form %}
        </div>
    </div>
{% endblock %}