pdp/forum/urls.py
# coding: utf-8

from django.conf.urls import patterns, url

import views

urlpatterns = patterns('',
    # Deprecated URLs, have to be checked before new ones to avoid conflict
    url(r'^sujet/(?P<topic_pk>\d+)-(?P<topic_slug>.+)$',
        views.deprecated_topic_redirect),
    url(r'^(?P<cat_slug>.+)/(?P<forum_pk>\d+)-(?P<forum_slug>.+)/$',
        views.deprecated_details_redirect),
    url(r'^(?P<cat_pk>\d+)-(?P<cat_slug>.+)/$',
        views.deprecated_cat_details_redirect),


    # Viewing a thread
    url(r'^sujet/nouveau$', views.new),
    url(r'^sujet/editer$', views.edit),
    url(r'^sujet/(?P<topic_pk>\d+)/(?P<topic_slug>.+)$', views.topic),

    # Message-related
    url(r'^message/editer$', views.edit_post),
    url(r'^message/nouveau$', views.answer),
    url(r'^message/utile$', views.useful_post),
    
    # Forum details
    
    url(r'^(?P<cat_slug>.+)/(?P<forum_slug>.+)/$',
        views.details),

    # Forums belonging to one category
    url(r'^(?P<cat_slug>.+)/$', views.cat_details),

    # Home
    url(r'^$', views.index),  
)

pdp/urls.py
# coding: utf-8

from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

import pages.views
import settings

urlpatterns = patterns('',
    url(r'^articles/', include('pdp.article.urls')),
    url(r'^tutoriels/', include('pdp.tutorial.urls')),
    url(r'^forums/', include('pdp.forum.urls')),
    url(r'^membres/', include('pdp.member.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^pages/', include('pdp.pages.urls')),

    url(r'^captcha/', include('captcha.urls')),

    url(r'^$', pages.views.home),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    )

pdp/forum/models.py
# coding: utf-8

from math import ceil
from datetime import datetime
import pytz

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify

from pdp.utils import get_current_user

POSTS_PER_PAGE = 21
SPAM_LIMIT_SECONDS = 60*15

class Category(models.Model):
    '''A category, containing forums'''
    class Meta:
        verbose_name = 'Catégorie'
        verbose_name_plural = 'Catégories'

    title = models.CharField('Titre', max_length=80)
    position = models.IntegerField('Position', null=True, blank=True)
    slug = models.SlugField()

    def __unicode__(self):
        '''Textual form of a category'''
        return self.title

    def get_absolute_url(self):
        return '/forums/{0}/'.format(self.slug)

    def get_forums(self):
        return Forum.objects.all()\
                .filter(category=self)\
                .order_by('position_in_category')


class Forum(models.Model):
    '''A forum, containing topics'''
    class Meta:
        verbose_name = 'Forum'
        verbose_name_plural = 'Forums'

    title = models.CharField('Titre', max_length=80)
    subtitle = models.CharField('Sous-titre', max_length=200)

    category = models.ForeignKey(Category, verbose_name='Catégorie')
    position_in_category = models.IntegerField('Position dans la catégorie',
                                               null=True, blank=True)
    
    slug = models.SlugField()

    def __unicode__(self):
        '''Textual form of a forum'''
        return self.title

    def get_absolute_url(self):
        return '/forums/{0}/{1}/'.format( \
            self.category.slug,
            self.slug,
        )

    def get_topic_count(self):
        '''Gets the number of threads in the forum'''
        return Topic.objects.all().filter(forum__pk=self.pk).count()

    def get_post_count(self):
        return Post.objects.all().filter(topic__forum=self).count()

    def get_last_message(self):
        '''Gets the last message on the forum, if there are any'''
        try:
            return Post.objects.all().filter(topic__forum__pk=self.pk).order_by('-pubdate')[0]
        except IndexError:
            return None

    def is_read(self):
        for t in Topic.objects.all().filter(forum=self):
            if never_read(t):
                return False
        return True


class Topic(models.Model):
    '''A thread, containing posts'''
    class Meta:
        verbose_name = 'Sujet'
        verbose_name_plural = 'Sujets'

    title = models.CharField('Titre', max_length=80)
    subtitle = models.CharField('Sous-titre', max_length=200)

    forum = models.ForeignKey(Forum, verbose_name='Forum')
    author = models.ForeignKey(User, verbose_name='Auteur')
    last_message = models.ForeignKey('Post', null=True,
                                     related_name='last_message',
                                     verbose_name='Dernier message')
    pubdate = models.DateTimeField('Date de création', auto_now_add=True)

    is_solved = models.BooleanField('Est résolu')
    is_locked = models.BooleanField('Est verrouillé')
    is_sticky = models.BooleanField('Est en post-it')

    def __unicode__(self):
        '''
        Textual form of a thread
        '''
        return self.title

    def get_absolute_url(self):
        return '/forums/sujet/{0}/{1}'.format(self.pk, slugify(self.title))

    def get_post_count(self):
        '''
        Return the number of posts in the topic
        '''
        return Post.objects.all().filter(topic__pk=self.pk).count()

    def get_last_answer(self):
        '''
        Gets the last answer in the thread, if any
        '''
        last_post = Post.objects.all()\
                .filter(topic__pk=self.pk)\
                .order_by('-pubdate')[0]
        
        if last_post == self.first_post():
            return None
        else:
            return last_post

    def first_post(self):
        '''
        Return the first post of a topic, written by topic's author
        '''
        return Post.objects\
            .filter(topic=self)\
            .order_by('pubdate')[0]

    def last_read_post(self):
        '''
        Return the last post the user has read
        '''
        try:
            return TopicRead.objects\
                .select_related()\
                .filter(topic=self, user=get_current_user())\
                .latest('post__pubdate').post
        except Post.DoesNotExist:
            return self.first_post()

    def is_followed(self, user=None):
        '''
        Check if the topic is currently followed by the user. This method uses
        the TopicFollowed objects.
        '''
        if user is None:
            user = get_current_user()

        try:
            TopicFollowed.objects.get(topic=self, user=user)
        except TopicFollowed.DoesNotExist:
            return False
        return True

    def antispam(self, user=None):
        '''
        Check if the user is allowed to post in a topic according to the
        SPAM_LIMIT_SECONDS value. If user shouldn't be able to post, then
        antispam is activated and this method returns True. Otherwise time
        elapsed between user's last post and now is enough, and the method will
        return False.
        '''
        if user is None:
            user = get_current_user()

        last_user_posts = Post.objects\
            .filter(topic=self)\
            .filter(author=user)\
            .order_by('-pubdate')

        if last_user_posts and last_user_posts[0] == self.get_last_answer():
            last_user_post = last_user_posts[0]
            t = timezone.now() - last_user_post.pubdate
            if t.total_seconds() < SPAM_LIMIT_SECONDS:
                return True

        return False
    
    def never_read(self):
        return never_read(self)
    


class Post(models.Model):
    '''
    A forum post written by an user.
    '''
    topic = models.ForeignKey(Topic, verbose_name='Sujet')
    author = models.ForeignKey(User, verbose_name='Auteur')
    text = models.TextField('Texte')

    pubdate = models.DateTimeField('Date de publication', auto_now_add=True)
    update = models.DateTimeField('Date d\'édition', null=True, blank=True)

    position_in_topic = models.IntegerField('Position dans le sujet')

    is_useful = models.BooleanField('Est utile', default=False)

    def __unicode__(self):
        '''Textual form of a post'''
        return u'<Post pour "{0}", #{1}>'.format(self.topic, self.pk)

    def get_absolute_url(self):
        page = int(ceil(float(self.position_in_topic) / POSTS_PER_PAGE))

        return '{0}?page={1}#p{2}'.format(self.topic.get_absolute_url(), page, self.pk)


class TopicRead(models.Model):
    '''
    Small model which keeps track of the user viewing topics. It remembers the
    topic he looked and what was the last Post at this time.
    '''
    class Meta:
        verbose_name = 'Sujet lu'
        verbose_name_plural = 'Sujets lus'

    topic = models.ForeignKey(Topic)
    post = models.ForeignKey(Post)
    user = models.ForeignKey(User)

    def __unicode__(self):
        return u'<Sujet "{0}" lu par {1}, #{2}>'.format(self.topic,
                                                self.user,
                                                self.post.pk)


class TopicFollowed(models.Model):
    '''
    Small model which keeps track of the topics followed by an user. If an
    instance of this model is stored with an user and topic instance, that
    means that this user is following this topic.
    '''
    class Meta:
        verbose_name = 'Sujet suivi'
        verbose_name_plural = 'Sujets suivis'

    topic = models.ForeignKey(Topic)
    user = models.ForeignKey(User)

    def __unicode__(self):
        return u'<Sujet "{0}" suivi par {1}>'.format(self.topic.title,
                                               self.user.username)


def never_read(topic, user=None):
    '''
    Check if a topic has been read by an user since it last post was added.
    '''
    if user is None:
        user = get_current_user()

    return TopicRead.objects\
        .filter(post=topic.last_message, topic=topic, user=user)\
        .count() == 0


def mark_read(topic):
    '''
    Mark a topic as read for the user
    '''
    TopicRead.objects.filter(topic=topic, user=get_current_user()).delete()
    t = TopicRead(
        post=topic.last_message, topic=topic, user=get_current_user())
    t.save()



def follow(topic):
    '''
    Toggle following of a topic for an user
    '''
    try:
        existing = TopicFollowed.objects.get(topic=topic, user=get_current_user())
    except TopicFollowed.DoesNotExist:
        existing = None

    if not existing:
        # Make the user follow the topic
        t = TopicFollowed(
            topic=topic,
            user=get_current_user()
        )
        t.save()
    else:
        # If user is already following the topic, we make him don't anymore
        existing.delete()


def get_last_topics():
    '''
    Returns the 3 very last topics
    '''
    return Topic.objects.all().order_by('-pubdate')[:3]

pdp/forum/forms.py
# coding: utf-8

from django import forms


class TopicForm(forms.Form):
    title = forms.CharField(max_length=80)
    subtitle = forms.CharField(max_length=255, required=False)
    text = forms.CharField(widget=forms.Textarea)


class PostForm(forms.Form):
    text = forms.CharField(widget=forms.Textarea)

templates/forum/answer.html
{% extends "forum/base.html" %}

{% block title %}
    Répondre au sujet
{% endblock %}

{% block headline %}
    Répondre au sujet
{% endblock %}

{% block headline-sub %}
    {{ topic.title }}
{% endblock %}

{% block breadcrumb %}
    <li><a href="{{ topic.forum.category.get_absolute_url }}">{{ topic.forum.category.title }}</a></li>
    <li><a href="{{ topic.forum.get_absolute_url }}">{{ topic.forum.title }}</a></li>
    <li><a href="{{ topic.get_absolute_url }}">{{ topic.title }}</a></li>
    <li class="current"><a href="#">Répondre au sujet</a></li>
{% endblock %}

{% block content %}

{% if newpost %}
<div class="row">
    <div class="large-12 columns">
        <div class="alert-box alert">
            <strong>Au moins un nouveau message a été posté</strong> dans la discussion
            pendant que vous rédigiez le votre.
        </div>
    </div>
</div>
{% endif %}

<div class="row">
    <div class="large-12">
        <form action="#previsualisation" method="POST">
            <textarea class="input-block-level" name="text" rows="20" id="id_text"
                placeholder="Contenu de votre message au format Markdown.">{{ text }}</textarea>
        
            <div style="text-align: center;">
                <button type="submit" class="button">
                    <i class="icon-ok icon-white"></i>
                    Répondre
                </button>
        
                <button type="submit" name="preview" class="button secondary">
                    <i class="icon-eye-open"></i>
                    Prévisualisation
                </button>
        
                <a href="{{ topic.get_absolute_url }}" class="button secondary">
                    <i class="icon-remove"></i>
                    Annuler
                </a>
            </div>
        
            <input type="hidden" name="last_post" value="{{ last_post_pk }}" />
            {% csrf_token %}
        </form>
    </div>
</div>

{% if text %}
    {% include "forum/previsualization.part.html" %}
{% endif %}

{% endblock %}

templates/forum/base.html
{% extends "base.html" %}

{% block title_base %}
    &#183; Forums
{% endblock %}

{% block breadcrumb_base %}
    <li><a href="{% url pdp.forum.views.index %}">Forums</a></li>
{% endblock %}

{% block menu_forum %}
    class="active"
{% endblock %}

templates/forum/cat_details.html
{% extends "forum/base.html" %}

{% block title %}
    {{ category.title }}
{% endblock %}

{% block headline %}
    {{ category.title }}
{% endblock %}

{% block breadcrumb %}
    <li class="current"><a href="#">{{ category.title }}</a></li>
{% endblock %}

{% block content %}
    
{% include "forum/forums_common.html" %}

{% endblock %}

templates/forum/details.html
{% extends "forum/base.html" %}
{% load humane_date %}

{% block title %}
    {{ forum.title }}
{% endblock %}

{% block headline %}
    {{ forum.title }}
{% endblock %}

{% block headline-sub %}
    {{ forum.subtitle }}
{% endblock %}

{% block breadcrumb %}
    <li><a href="{{ forum.category.get_absolute_url }}">{{ forum.category.title }}</a></li>
    <li class="current"><a href="#">{{ forum.title }}</a></li>
{% endblock %}

{% block headline-actions %}
    {% if user.is_authenticated %}
        <p>
            <a href="/forums/sujet/nouveau?forum={{ forum.pk }}" class="button">
                Nouveau sujet
            </a>
        </p>
    {% endif %}
{% endblock %}

{% block content %}


{% if sticky_topics %}
    <div class="forum-entries forum-entries-sticky">
        {% for topic in sticky_topics %}
            {% include "forum/details_row.part.html" %}
        {% endfor %}
    </div>
{% endif %}

<div class="forum-entries">
    {% for topic in topics %}
        {% include "forum/details_row.part.html" %}
    {% endfor %}
</div>

{% endblock %}

templates/forum/details_row.part.html
{% load humane_date %}
{% load upfirstletter %}

<div class="forum-entry
    {% if topic.is_locked %}
        forum-entry-locked
    {% else %}
        {% if topic.is_solved %}
        forum-entry-solved
        {% endif %}
    {% endif %}">
    <div class="forum-entry-title
    {% if user.is_authenticated %}
        {% if topic.never_read %}
            unread
        {% endif %}
    {% endif %}">
        <a href="{{ topic.get_absolute_url }}">
            {{ topic.title }}
        </a>
        {% if topic.subtitle %}
            <p>
                {{ topic.subtitle }}
            </p>
        {% endif %}
    </div>
    <div class="forum-entry-count">
        <span class="label">
            {{ topic.get_post_count|add:"-1" }}
        </span>
    </div>
    <div class="forum-entry-desc">
        <p>
            {% with member=topic.author %}
                Par {% include "member/member_item_common.part.html" %}
            {% endwith %}
            <br />
            {% with answer=topic.get_last_answer %}
                {% if answer %}
                    Dernière rép.
                    <a href="{{ answer.get_absolute_url }}">
                        {% with date=answer.pubdate|humane_date %}
                            {{ date }}
                        {% endwith %}
                    </a>
                    par
                    {% with member=answer.author %}
                        {% include "member/member_item_common.part.html" %}
                    {% endwith %}
                {% else %}
                    aucune réponse
                {% endif %}
            {% endwith %}
            
        </p>
    </div>
</div>

{% if topic.is_sticky %}
    <i class="icon-bookmark" title="Ce sujet est épinglé"></i>
{% endif %}
{% if topic.is_locked %}
    <i class="icon-lock" title="Ce sujet est verrouillé"></i>
{% endif %}
{% if topic.is_solved %}
    <i class="icon-ok" title="Ce sujet est résolu"></i>
{% endif %}

{% if user.is_authenticated %}
    {% with topic.last_read_post as last_read_post %}
        {% ifnotequal last_read_post topic.get_last_answer %}
            <i class="icon-eye-open"></i>
        {% endifnotequal %}
    {% endwith %}
{% endif %}

templates/forum/edit_post.html
{% extends "forum/base.html" %}

{% block title %}
    Éditer un message
{% endblock %}

{% block headline %}
    Éditer un message
{% endblock %}

{% block breadcrumb %}
    <li><a href="{{ post.topic.forum.category.get_absolute_url }}">{{ post.topic.forum.category.title }}</a></li>
    <li><a href="{{ post.topic.forum.get_absolute_url }}">{{ post.topic.forum.title }}</a></li>
    <li><a href="{{ post.topic.get_absolute_url }}">{{ post.topic.title }}</a></li>
    <li class="current"><a href="#">Éditer un message</a></li>
{% endblock %}

{% block content %}
    
<div class="row">
    <div class="large-12 columns">
        <form action="#previsualisation" method="POST" class="form-horizontal">
            {% if topic %}
            <fieldset>
                <legend>Sujet</legend>
                <div class="control-group">
                    <label class="control-label" for="id_title">Titre</label>
                    <div class="controls">
                        <input type="text" name="title" id="id_title"
                            class="input-xxlarge" value="{{ topic.title }}" />
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="id_subtitle">Sous titre</label>
                    <div class="controls">
                        <input type="text" name="subtitle" id="id_subtitle"
                            class="input-xxlarge" value="{{ topic.subtitle }}" />
                    </div>
                </div>
            </fieldset>
            {% endif %}
            <fieldset>
                <legend>Message</legend>
                <div class="control-group">
                    <label class="control-label" for="id_text">Texte</label>
                    <div class="controls">
                        <textarea id="id_text" name="text"
                            class="input-block-level" rows="20">{{ text }}</textarea>
                    </div>
                </div>
            </fieldset>
        
            <div style="text-align: center;">
                <button type="submit" class="button">
                    Éditer
                </button>
        
                <button type="submit" name="preview" class="button secondary">
                    Prévisualisation
                </button>
        
                <a href="{{ post.get_absolute_url }}" class="button secondary">Annuler</a>
            </div>
        
            {% csrf_token %}
        </form>
    </div>
</div>

{% include "forum/previsualization.part.html" %}

{% endblock %}

templates/forum/forums_common.html
{# Block displaying the list of forums belonging to a category #}
{% load humane_date %}
{% load upfirstletter %}

{% for forum in category.get_forums %}
<div class="forum-entry">
    <div class="forum-entry-title {% if user.is_authenticated and not forum.is_read %}unread{% endif %}">
        <a href="{{ forum.get_absolute_url }}">
            {{ forum.title }}
        </a>
        <p>
            {{ forum.subtitle }}
        </p>
    </div>
    <div class="forum-entry-count">
        <span class="label">
            {{ forum.get_topic_count }}
        </span>
        <span class="label secondary">
            {{ forum.get_post_count }}
        </span>
    </div>
    <div class="forum-entry-count">
        
    </div>
    <div class="forum-entry-desc">
        <p>
            {% with last_message=forum.get_last_message %}
                {% if last_message %}
                    <a href="{{ last_message.get_absolute_url }}">
                        {% with date=last_message.pubdate|humane_date %}
                            {{ date|upfirstletter }}
                        {% endwith %}
                    </a>
                    par
                    {% with member=last_message.author %}
                        {% include "member/member_item_common.part.html" %}
                    {% endwith %}
                    dans
                    <a href="{{ last_message.topic.get_absolute_url }}">
                        {{ last_message.topic.title }}
                    </a>
                {% else %}
                    Aucun message
                {% endif %}
            {% endwith %}
        </p>
    </div>
</div>
    
{% endfor %}

templates/forum/index.html
{% extends "forum/base.html" %}

{% block title %}
    Liste des forums
{% endblock %}

{% block meta %}
    <meta name="description" content="Les forums vous permettent de venir poser
    vos questions aux autres membres mais aussi de s'entrainer ou tout
    simplement de discuter.  Cela fonctionne également dans l'autre sens : vous
    pouvez ici aider les autres et proposer des exercices au reste de la
    communauté." />
{% endblock %}

{% block header %}
    <h1>Forums</h1>
    <p>
        Les forums vous permettent de venir poser vos questions aux autres membres mais aussi de s'entrainer ou <strong>tout simplement de discuter</strong>.
        Cela fonctionne également dans l'autre sens : vous pouvez ici aider les autres et proposer des exercices au reste de la communauté.
    </p>
{% endblock %}

{% block headline %}
   Liste des forums
{% endblock %}

{% block breadcrumb %}
    <a class="current" href="#">Index</a>
{% endblock %}

{% block content %}

{% for category in categories %}
    <div class="row">
        <div class="large-12 columns">
            <h2>
                {{ category.title }}
            </h2>
        </div>
    </div>
    {% include "forum/forums_common.html" %}
{% endfor %}

{% endblock %}

templates/forum/new.html
{% extends "forum/base.html" %}
{% load emarkdown %}
{% load markup %}

{% block title %}
    Nouveau sujet
{% endblock %}

{% block headline %}
    Nouveau sujet
{% endblock %}

{% block breadcrumb %}
    <li><a href="{{ forum.category.get_absolute_url }}">{{ forum.category.title }}</a></li>
    <li><a href="{{ forum.get_absolute_url }}">{{ forum.title }}</a></li>
    <li class="current"><a href="#">Nouveau sujet</a></li>
{% endblock %}

{% block content %}
<div class="row">
    <div class="large-12 columns">
        <form action="" method="POST">
            <input type="text" placeholder="Titre" name="title" class="input-xxlarge" value="{{ title }}" /><br />
            <input type="text" placeholder="Sous-titre" name="subtitle" class="input-xxlarge" value="{{ subtitle }}" /><br />
            <textarea class="input-block-level" rows="20" name="text" id="id_text"
                placeholder="Contenu de votre message au format Markdown.">{{ text }}</textarea>

            <div style="text-align: center;">
                <button type="submit" class="button">
                    <i class="icon-plus icon-white"></i>
                    Nouveau sujet
                </button>

                <button type="submit" name="preview" class="button secondary">
                    Prévisualisation
                </button>

                <a href="{{ forum.get_absolute_url }}" class="button secondary">
                    Retour
                </a>
            </div>

            {% csrf_token %}
        </form>
    </div>
</div>

{% if text %}
<div class="row">
    <div class="large-12 columns">
        <div class="panel">
            <h5>Prévisualisation de votre message</h5>
            {{ text|emarkdown }}
        </div>
    </div>
</div>
{% endif %}

{% endblock %}

templates/forum/previsualization.part.html
{% load emarkdown %}
<div class="row" id="previsualisation">
    <div class="large-12 columns">
        <div class="panel">
            <h5>Prévisualisation de votre message</h5>
            {{ text|emarkdown }}
        </div>
    </div>
</div>

templates/forum/topic_item_common.part.html
{% load humane_date %}


<a href="{{ topic.get_absolute_url }}">
    {{ topic.title }}
</a>
<p>
    {{ topic.subtitle }}
</p>

templates/forum/topic_pagination.part.html
<div class="row">
    <div class="large-12 columns">
        <div class="pagination-centered">
            <ul class="pagination">
                <li class="arrow {% ifequal nb 1 %}unavaible{% endifequal %}">
                    <a href="{% ifnotequal nb 1 %}{{ topic.get_absolute_url }}?page={{ nb|add:"-1" }}{% else %}javascript:;{% endifnotequal %}">
                        «
                    </a>
                </li>
            
                {% for page in pages %}
                    <li class="{% ifequal page nb %}current{% endifequal %}">
                        <a href="{% ifnotequal page nb %}{{ topic.get_absolute_url }}?page={{ page }}{% else %}javascript:;{% endifnotequal %}">
                            {{ page }}
                        </a>
                    </li>
                {% endfor %}
                
                <li class="arrow {% ifequal nb pages|last %}unavaible{% endifequal %}">
                    <a href="{% ifnotequal nb pages|last %}{{ topic.get_absolute_url }}?page={{ nb|add:"1" }}{% else %}javascript:;{% endifnotequal %}">
                        »
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>